package com.matthewadev.render;

public enum BlockType {
    EMPTY,
    STONE,
    DIRT,
    GRASS_BLOCK,
    ACACIA_LOG,
    BIRCH_LOG,
    DARK_OAK_LOG,
    JUNGLE_LOG,
    OAK_LOG,
    SPRUCE_LOG,
    SPRUCE_PLANKS,
    OAK_PLANKS,
    JUNGLE_PLANKS,
    ACACIA_PLANKS,
    BIRCH_PLANKS,
    DARK_OAK_PLANKS,
    BLACK_WOOL,
    BLUE_WOOL,
    BROWN_WOOL,
    CYAN_WOOL,
    GRAY_WOOL,
    LIGHT_BLUE_WOOL,
    LIGHT_GRAY_WOOL,
    LIME_WOOL,
    MAGENTA_WOOL,
    GREEN_WOOL,
    ORANGE_WOOL,
    PINK_WOOL,
    PURPLE_WOOL,
    RED_WOOL,
    WHITE_WOOL,
    YELLOW_WOOL,
    CHISELED_STONE_BRICKS,
    CRACKED_STONE_BRICKS,
    CRAFTING_TABLE,
    END_STONE,
    GLASS,
    LEAVES,
    SMOOTH_STONE,
    STONE_BRICKS;
    public static boolean isTransparent(BlockType b){
        return b == GLASS || b == LEAVES;
    }
}
